### ISSUE TITLE
Raspberry inotify-tools

### ISSUE THREAD

**Issue by SpolusApps** [MirServer/mir-kiosk-snap-launch#18]
Hi

I'm doing a test generating a version with flutter for arm64 using raspberry 4 and it always returns this error:

/snap/super-cool-app/x6/bin/wayland-launch: 22: /snap/super-cool-app/x6/bin/wayland-launch: inotifywait: Exec format error

Can someone help me?

**Comment by wmww** [comment]
Hmm, sounds like you possibly have an x86 version of inotifywait. I wonder why that might be? Unfortunately I don't have a pi to test on at the moment.

**Comment by AlanGriffiths** [comment]
> sounds like you possibly have an x86 version of inotifywait

Agreed: That is probably the problem.

@SpolusApps, this can happen because you're building on `amd64` and running on `arm64`. Your architecture clause should look like:

```yaml
architectures:
  - build-on: arm64
```

Don't think that `run-on` magically makes `amd64` binaries work on `arm64`.  (This is all explained in detail on the snapcraft forums.)

**Comment by SpolusApps** [comment]
Hi Alan

I try to compile this way, because like you say my machine is am `amd64`...

In my case only generated  a `arm64` build with tun-on option:
```yaml
 architectures:
  - build-on: amd64
  - run-on: arm64
```
In thys case is when a receive >inotifywait error, i will try to compile on another raspberry with base arm64 native to see what happens.

One observation, i went check a binary inside the generated `snap`:
`/snap/wpe-webkit-mir-kiosk/45/usr/bin/inotifywait`

```console

dev@dev-VirtualBox:~/Downloads/flutterdemo$ file inotifywait 
inotifywait: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=80778fd10f3aca32b6c9d345fe29ed17d744b5d2, stripped
```

Aparentely the file is ok with the platform.

**Comment by AlanGriffiths** [comment]
>  architectures:
>   - build-on: amd64
>   - run-on: arm64

You misunderstood these options. `build-on` means "package on". There's no cross-building feature, it just stages arm64. Unless you have multi-arch binaries (or scripts) you can't run on another architecture.

**Comment by Saviq** [comment]
@SpolusApps have a look at the documentation for architectures in snapcraft:

https://snapcraft.io/docs/architectures
