### ISSUE TITLE
Waiting for Wayland socket

### ISSUE THREAD

**Issue by jstiefel** [MirServer/mir-kiosk-snap-launch#4]
I'm continuously getting the message

```
+ [ ! -O /run/user/1000/wayland-0 ]
+ echo waiting for Wayland socket
waiting for Wayland socket
+ sleep 4
```
when running this on Ubuntu Core 18. What does this mean? I don't have the wayland-0 file in /run/user/1000.

**Comment by AlanGriffiths** [comment]
It appears you're running a snap as a user account (id=1000), not as a daemon (id=0). That's not the usual way to do things on core (see the [README](https://github.com/MirServer/mir-kiosk-snap-launch/blob/master/README.md)). For that to work you'd need to provide a Wayland server running as user 1000.

The message reflects the absence of a suitable Wayland server.

**Comment by jstiefel** [comment]
Thank you for the explanation. This makes things clear now.
